### PR TITLE
Bugfix: this will prevent the bypass code to swallow exceptions

### PR DESCRIPTION
**Pull request by eliasdorneles**
The `return` in the `finally` block was causing exceptions to be swallowed and thus cause some jobs to fail silently.

Moving the `return True` to the try block fixes the issue.

I haven't written a test case for the bypass code, but you can verify the problem with this:

```
def some_func():
    try:
        print('will fail')
        raise ValueError("oops")
        print('this will never print')
    finally:
        print('Executing finally block')
        return True

some_func()
```

The snippet above will have the exception swallowed.

### CODE REVIEW

**Comment by bbotella** [comment]
Is this an urgent fix or we can wait to have that test?

**Comment by eliasdorneles** [comment]
@bbotella working on a test, will push soon :)

**Comment by bbotella** [comment]
Neat. Waiting for the build to finsh.

**Comment by bbotella** [comment]
This probably worths a patch release.

**Comment by eliasdorneles** [comment]
@bbotella want to do it? :)

**Comment by bbotella** [comment]
On it.

**Comment by eliasdorneles** [comment]
@bbotella Yay! with metadata it looks much better in future PyPI: https://pypi.io/project/exporters :)

**Pull request merged**
